defmodule TwitchApi.Ads.StartCommercial do
  @moduledoc """
  ⛔ This module is autogenerated please do not modify manually.

  ## Example request from twitch api docs:
  ### descriptions:
  This request starts a commercial.
  
  ### requests:
  curl -X POST 'https://api.twitch.tv/helix/channels/commercial'  
   -H'Authorization: Bearer 2gbdx6oar67tqtcmt49t3wpcgycthx'  
   -H'Client-Id: wbmytr93xzw8zbg0p1izqyzzc5mbiz'  
   -H'Content-Type: application/json'  
   --data-raw'{
    "broadcaster_id": "41245072",
    "length": 60
   }'
  

  ## Example response from twitch api docs:
  ### descriptions:
  
  ### responses:
  {"data":[{"length":60,"message":"","retry_after":480}]}
  

  """

  alias TwitchApi.MyFinch


  @doc """
  ### Description:
  Starts a commercial on a specified channel.

  ### Required authentication:
  OAuth Token required
  Required scope: channel:edit:commercial
  """

  @spec call(%{required(:broadcaster_id) => String.t(), # ID of the channel requesting a commercialMinimum =>  1 Maximum =>  1
    required(:length) => integer, # Desired length of the commercial in seconds. Valid options are 30 60 90 120 150 180.
    }| nil) :: {:ok, Finch.Response.t} | {:error, Exception.t}
  def call(body_params) do
    MyFinch.request("POST","https://api.twitch.tv/helix/channels/commercial",
    TwitchApi.ApiJson.Template.Method.Headers.config_headers(), body_params)
  end

end
