defmodule TwitchApi.Ads.StartCommercial.NotSupported do
  @moduledoc """
  ⛔ This module is autogenerated please do not modify manually.

  ## Example request from twitch api docs:
  ### descriptions:
  This request starts a commercial.

  ### requests:
  curl -X POST 'https://api.twitch.tv/helix/channels/commercial'  
   -H'Authorization: Bearer 2gbdx6oar67tqtcmt49t3wpcgycthx'  
   -H'Client-Id: wbmytr93xzw8zbg0p1izqyzzc5mbiz'  
   -H'Content-Type: application/json'  
   --data-raw'{
    "broadcaster_id": "41245072",
    "length": 60
   }'


  ## Example response from twitch api docs:
  ### descriptions:

  ### responses:
  {"data":[{"length":60,"message":"","retry_after":480}]}


  """

  # API method not supported
end
