defmodule TwitchApi.Music.GetSoundtrackCurrentTrack do
  @moduledoc """
  ⛔ This module is autogenerated please do not modify manually.

  ## Example request from twitch api docs:
  ### descriptions:

  ### requests:
  curl -X GET 'https://api.twitch.tv/helix/soundtrack/current_track?broadcaster_id=1234'  
   -H'Authorization: Bearer 4a4x78f5wqvkybms7mxfist3jmzul'  
   -H'Client-Id: t214nt8z1rdtbj69hyarjvh5mi6fh'


  ## Example response from twitch api docs:
  ### descriptions:

  ### responses:
  {"data":[{"track":{"artists":[{"id":"B07S7JG3TK","name":"Enoth","creator_channel_id":"39051113"}],"id":"B08D6QFS38","isrc":"CCXXXYYNNNNN","duration":153,"title":"Please stay","album":{"id":"B08D6PMKYL","name":"Summer 2020","image_url":"https://m.media-amazon.com/images/I/51zs1JZY8tL.jpg"}},"source":{"id":"B08HCW84SF","content_type":"PLAYLIST","title":"Beats To Stream To","image_url":"https://m.media-amazon.com/images/I/419WuvMXzEL.jpg","soundtrack_url":"https://soundtrack.twitch.tv/playlist?playlistID=B08HCW84SF","spotify_url":"https://open.spotify.com/playlist/1LOP14236oTUscowY3NvYN"}}]}


  """

  alias TwitchApi.MyFinch
  alias TwitchApi.ApiJson.Template.Method.Headers

  @doc """
  ### Description:
  BETA Gets the Soundtrack track that the broadcaster is playing.

  ### Required authentication:


  ### Required authorization:
  Requires an App access token or User access token.
  """

  @typedoc """
  The ID of the broadcaster that’s playing a Soundtrack track.
  """
  @type broadcaster_id :: %{required(:broadcaster_id) => String.t()}

  @spec call(broadcaster_id) :: {:ok, Finch.Response.t()} | {:error, Exception.t()}
  def call(%{broadcaster_id: broadcaster_id}) do
    MyFinch.request(
      "GET",
      "https://api.twitch.tv/helix/soundtrack/current_track?broadcaster_id=#{broadcaster_id}",
      Headers.config_headers(),
      nil
    )
  end
end
