defmodule TwitchApi.Charity.GetCharityCampaign do
  @moduledoc """
  ⛔ This module is autogenerated please do not modify manually.

  ## Example request from twitch api docs:
  ### descriptions:
  Gets the broadcaster’s active charity campaign.

  ### requests:
  curl -X GET 'https://api.twitch.tv/helix/charity/campaigns?broadcaster_id=123456'  
   -H'Authorization: Bearer kpvy3cjboyptmiacwr0c19hotn5s'  
   -H'Client-Id: hof5gwx0su6owfn0nyan9c87zr6t'


  ## Example response from twitch api docs:
  ### descriptions:

  ### responses:
  {"data":[{"id":"123-abc-456-def","broadcaster_id":"123456","broadcaster_name":"SunnySideUp","broadcaster_login":"sunnysideup","charity_name":"Example name","charity_description":"Example description","charity_logo":"https://example.url/logo.png","charity_website":"https://www.example.com","current_amount":{"value":86000,"decimal_places":2,"currency":"USD"},"target_amount":{"value":1500000,"decimal_places":2,"currency":"USD"}}]}


  """

  alias TwitchApi.MyFinch
  alias TwitchApi.ApiJson.Template.Method.Headers

  @doc """
  ### Description:
  BETA Gets information about the broadcaster’s active charity campaign.

  ### Required authentication:


  ### Required authorization:
  Requires a user access token that includes the channel:read:charity scope. The ID in the broadcaster_id query parameter must match the user ID in the access token.
  """

  @typedoc """
  The ID of the broadcaster that’s actively running a charity campaign.
  """
  @type broadcaster_id :: %{required(:broadcaster_id) => String.t()}

  @spec call(broadcaster_id) :: {:ok, Finch.Response.t()} | {:error, Exception.t()}
  def call(%{broadcaster_id: broadcaster_id}) do
    MyFinch.request(
      "GET",
      "https://api.twitch.tv/helix/charity/campaigns?broadcaster_id=#{broadcaster_id}",
      Headers.config_headers(),
      nil
    )
  end
end
