defmodule TwitchApi.Extensions.CreateExtensionSecret.NotSupported do
  @moduledoc """
  ⛔ This module is autogenerated please do not modify manually.

  ## Example request from twitch api docs:
  ### descriptions:
  
  ### requests:
  curl -X POST 'https://api.twitch.tv/helix/extensions/jwt/secrets?extension_id=uo6dggojyb8d6soh92zknwmi5ej1q2&delay=600'  
   -H'Authorization: Bearer cfabdegwdoklmawdzdo98xt2fo512y'  
   -H'Client-Id: uo6dggojyb8d6soh92zknwmi5ej1q2'
  

  ## Example response from twitch api docs:
  ### descriptions:
  
  ### responses:
  {"data":[{"format_version":1,"secrets":[{"content":"old-secret","active_at":"2021-03-29T06:58:40.858343036Z","expires_at":"2021-04-22T05:21:54.99261682Z"},{"content":"new-secret","active_at":"2021-04-22T04:16:54.996365329Z","expires_at":"2121-03-29T04:16:54.996365329Z"}]}]}
  

  """


  # API method not supported
end
