defmodule TwitchApi.Extensions.GetExtensionConfigurationSegment.NotSupported do
  @moduledoc """
  ⛔ This module is autogenerated please do not modify manually.

  ## Example request from twitch api docs:
  ### descriptions:
  This example gets the global configuration segment from the specified extension. Because the request gets the global segment, it must not include the broadcaster_id query parameter.
  The following example shows a global segment that contains a plain text string in the content field.
  The following example shows a global segment that contains a string-encoded JSON object in the content field.
  
  ### requests:
  
  curl -X GET 'https://api.twitch.tv/helix/extensions/configurations?extension_id=<your extension id>&segment=global'  
   -H'Authorization: Bearer <your JWT token>'  
   -H'Client-Id: <your client ID>'
  

  ## Example response from twitch api docs:
  ### descriptions:
  
  ### responses:
  {"data":[{"segment":"global","content":"{\"foo\":\"bar\"}","version":"0.0.1"}]}
  content
  {"data":[{"segment":"global","content":"hello config!","version":"0.0.1"}]}
  content
  broadcaster_id
  

  """


  # API method not supported
end
