defmodule TwitchApi.Extensions.SetExtensionConfigurationSegment do
  @moduledoc """
  ⛔ This module is autogenerated please do not modify manually.

  ## Example request from twitch api docs:
  ### descriptions:
  
  ### requests:
  curl -X PUT 'https://api.twitch.tv/helix/extensions/configurations'  
   -H'Authorization: Bearer cfabdegwdoklmawdzdo98xt2fo512y'  
   -H'Client-Id: uo6dggojyb8d6soh92zknwmi5ej1q2'  
   -d'{
    "extension_id": "uo6dggojyb8d6soh92zknwmi5ej1q2",
    "segment": "global",
    "version": "0.0.1",
    "content": "hello config!"
   }'
  

  ## Example response from twitch api docs:
  ### descriptions:
  
  ### responses:
  204NoContent
  

  """

  alias TwitchApi.MyFinch


  @doc """
  ### Description:
  NEW Sets a single configuration segment of any type. The segment type is specified as a body parameter.

  ### Required authentication:
  
  """

  @spec call(%{required(:extension_id) => String.t(), # ID for the Extension which the configuration is for.
    required(:segment) => String.t(), # Configuration type. Valid values are \global\ \developer\ or \broadcaster\.
    }| nil) :: {:ok, Finch.Response.t} | {:error, Exception.t}
  def call(body_params) do
    MyFinch.request("PUT","https://api.twitch.tv/helix/extensions/configurations",
    TwitchApi.ApiJson.Template.Method.Headers.config_headers(), body_params)
  end

end
