defmodule TwitchApi.Channels.ModifyChannelInformation do
  @moduledoc """
  ⛔ This module is autogenerated please do not modify manually.

  ## Example request from twitch api docs:
  ### descriptions:
  
  ### requests:
  curl -X PATCH 'https://api.twitch.tv/helix/channels?broadcaster_id=41245072'  
   -H'Authorization: Bearer 2gbdx6oar67tqtcmt49t3wpcgycthx'  
   -H'Client-Id: wbmytr93xzw8zbg0p1izqyzzc5mbiz'  
   -H'Content-Type: application/json'  
   --data-raw'{"game_id":"33214", "title":"there are helicopters in the game? REASON TO PLAY FORTNITE found", "broadcaster_language":"en"}'
  

  ## Example response from twitch api docs:
  ### descriptions:
  
  ### responses:
  204NoContent
  

  """

  alias TwitchApi.MyFinch


  @doc """
  ### Description:
  Modifies channel information for users.

  ### Required authentication:
  OAuth Token required
  Required scope: channel:manage:broadcast
  """

  @typep broadcaster_id :: %{required(:broadcaster_id) => String.t()} # ID of the channel to be updated
  
  @spec call(broadcaster_id) :: {:ok, Finch.Response.t} | {:error, Exception.t}
  def call(%{broadcaster_id: broadcaster_id}) do
    MyFinch.request("PATCH","https://api.twitch.tv/helix/channels?broadcaster_id=#{broadcaster_id}",
    TwitchApi.ApiJson.Template.Method.Headers.config_headers(), nil)
  end

end
