defmodule TwitchApi.ChannelPoints.DeleteCustomReward.NotSupported do
  @moduledoc """
  ⛔ This module is autogenerated please do not modify manually.

  ## Example request from twitch api docs:
  ### descriptions:
  This request deletes a custom reward:

  ### requests:
  curl -X DELETE 'https://api.twitch.tv/helix/channel_points/custom_rewards?broadcaster_id=274637212&id=b045196d-9ce7-4a27-a9b9-279ed341ab28'  
   -H'Client-Id: gx2pv4208cff0ig9ou7nk3riccffxt'  
   -H'Authorization: Bearer vjxv3i0l4zxru966wsnwji51tmpkj2'


  ## Example response from twitch api docs:
  ### descriptions:

  ### responses:
  204 No Content



  """

  # API method not supported
end
