defmodule TwitchApi.Chat.GetGlobalChatBadges do
  @moduledoc """
  ⛔ This module is autogenerated please do not modify manually.

  ## Example request from twitch api docs:
  ### descriptions:
  Returns global chat badges.
  
  ### requests:
  curl -X GET 'https://api.twitch.tv/helix/chat/badges/global'  
   -H'Authorization: Bearer cfabdegwdoklmawdzdo98xt2fo512y'  
   -H'Client-Id: uo6dggojyb8d6soh92zknwmi5ej1q2'
  

  ## Example response from twitch api docs:
  ### descriptions:
  
  ### responses:
  {"data":[...{"set_id":"vip","versions":[{"id":"1","image_url_1x":"https://static-cdn.jtvnw.net/badges/v1/b817aba4-fad8-49e2-b88a-7cc744dfa6ec/1","image_url_2x":"https://static-cdn.jtvnw.net/badges/v1/b817aba4-fad8-49e2-b88a-7cc744dfa6ec/2","image_url_4x":"https://static-cdn.jtvnw.net/badges/v1/b817aba4-fad8-49e2-b88a-7cc744dfa6ec/3"}]},...]}
  

  """

  alias TwitchApi.MyFinch


  @doc """
  ### Description:
  NEW Gets a list of chat badges that can be used in chat for any channel.

  ### Required authentication:
  
  """

  @spec call() :: {:ok, Finch.Response.t} | {:error, Exception.t}
  def call() do
    MyFinch.request("GET","https://api.twitch.tv/helix/chat/badges/global",
    TwitchApi.ApiJson.Template.Method.Headers.config_headers(), nil)
  end

end
