defmodule TwitchApi.Streams.CreateStreamMarker.NotSupported do
  @moduledoc """
  ⛔ This module is autogenerated please do not modify manually.

  ## Example request from twitch api docs:
  ### descriptions:
  This creates a marker at the current location in user 123’s stream.

  ### requests:
  curl -X POST 'https://api.twitch.tv/helix/streams/markers'  
   -H'Authorization: Bearer cfabdegwdoklmawdzdo98xt2fo512y'  
   -H'Client-Id: uo6dggojyb8d6soh92zknwmi5ej1q2'  
   -H'Content-Type: application/json'  
   -d'{"user_id":"123", "description":"hello, this is a marker!"}'


  ## Example response from twitch api docs:
  ### descriptions:

  ### responses:
  {"data":[{"id":123,"created_at":"2018-08-20T20:10:03Z","description":"hello, this is a marker!","position_seconds":244}]}


  """

  # API method not supported
end
