defmodule TwitchApi.Videos.DeleteVideos.NotSupported do
  @moduledoc """
  ⛔ This module is autogenerated please do not modify manually.

  ## Example request from twitch api docs:
  ### descriptions:
  This example deletes two videos with the IDs 1234 and 9876.

  ### requests:
  curl -X DELETE 'https://api.twitch.tv/helix/videos?id=1234&id=9876'  
   -H'Authorization: Bearer 2gbdx6oar67tqtcmt49t3wpcgycthx'  
   -H'Client-Id: uo6dggojyb8d6soh92zknwmi5ej1q2'


  ## Example response from twitch api docs:
  ### descriptions:

  ### responses:
  {"data":["1234","9876"]}


  """

  # API method not supported
end
